org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+UseSerialGC -Dfile.encoding=UTF-8

android.useAndroidX=true

android.newDsl=false
android.builtInKotlin=false

kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false

org.gradle.caching=false
org.gradle.daemon=false
org.gradle.configuration-cache=false
org.gradle.parallel=false

android.enableR8.fullMode=false